version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.11.10
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.9
  - dependency-name: rollup-plugin-esbuild
    versions:
    - 4.1.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: parcel-bundler
    versions:
    - 1.12.5
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
